# Website basic configuration
site:
  title: "Machine Learning Tutorial"
  description: "Deep understanding of machine learning principles and applications"
  logo: "🤖"
  author: "AI Team"
  
# Top navigation configuration
navbar:
  items:
    - title: "Home"
      link: "/"
      active: true
    - title: "Documentation"
      link: "/docs"
    - title: "About"
      link: "/about"

# Sidebar navigation configuration
sidebar:
  sections:
    - title: "Chapter 1: Machine Learning Basics"
      path: "/chapter1"
      children:
        - title: "1.1 The Two Hands and Four Legs of AI"
          path: "/chapter1/ai-basics"
        - title: "1.2 What is Machine Learning"
          path: "/chapter1/what-is-ml"
        - title: "1.3 The Era That Created Machine Learning"
          path: "/chapter1/era-of-ml"
        - title: "1.4 Generalization: The Core of Machine Learning"
          path: "/chapter1/generalization"
        - title: "1.5 Inductive Bias: The Soul of Machine Learning"
          path: "/chapter1/inductive-bias"
        - title: "1.6 Limitations of Machine Learning"
          path: "/chapter1/limitations"
        - title: "1.7 Chapter Summary"
          path: "/chapter1/summary"
          
    - title: "Chapter 2: Mathematical Foundations"
      path: "/chapter2"
      children:
        - title: "2.1 Linear Algebra Basics"
          path: "/chapter2/linear-algebra"
        - title: "2.2 Probability Theory Basics"
          path: "/chapter2/probability"
        - title: "2.3 Calculus Basics"
          path: "/chapter2/calculus"

# Theme configuration
theme:
  # Theme selection: default | vue | github | purple | orange | emerald
  theme: "github"
  
  # Default mode: light | dark | auto
  defaultMode: "auto"
  
  # Allow users to toggle theme
  allowToggle: true
  
  # Show theme switcher (if false, users cannot manually switch themes)
  showThemeSwitcher: true

# Table of contents configuration
toc:
  # Maximum level to display in TOC (1-6)
  # 1: only h1
  # 2: h1, h2
  # 3: h1, h2, h3
  # and so on
  maxLevel: 2
  
  # Enable table of contents
  enabled: true
  
  # TOC title
  title: "Table of Contents" 